### ISSUE TITLE
Check on the form validation states

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#109] opened 2018-11-29 02:10 UTC
Once they've filled out some of the forms...sometimes they get error messages? Just make sure these are right.

**Comment by thekabistro** [comment] 2018-12-30 17:30
Covered in #121! Users get a lovely "Incomplete" profile and "Pending" messages as of now.

**Comment by shivanmodha** [comment] 2018-12-30 17:40
Actually, its almost done. Its not being saved in LCS properly, although the query is made. When you hit the "Update" button, the `registration_status` changes to registered, and then it shows `pending` because it updates the `this.state.user` attribute shows `registration_status = registered`. However, once you refresh the page, it shows you the incomplete message

**Comment by TresTres** [comment] 2018-12-30 19:33
This is partially my fault. There was a request last HackRU to change the wording of the status messages to the user, which was a reduction of the mapping of statuses that are recognized by lcs.  Basically I had another parent component manage the displayed the status and that kinda murks up the logic when fixing it.  If you bypass this and follow what is in `getStatus` in `UserActions` it might work?

**Comment by TresTres** [comment] 2018-12-30 19:48
Check legacy code for above btw my Redux bad

**Comment by shivanmodha** [comment] 2018-12-30 20:48
The issue is I can't even change the `registration_status` field in lcs at all through the update endpoint. I'm using the following curl to test it out, and its not working:
```
λ curl -X POST https://7c5l6v7ip3.execute-api.us-west-2.amazonaws.com/lcs-test/update -H "Content-Type: application/json" -d "{ \"updates\":{\"$set\": { \"registration_status\": \"registered\" }}, \"user_email\":\"TESTING123\",\"auth_email\":\"TESTING123\",\"auth\":<SOME TOKEN> \"query\": { \"email\":\"TESTING123\" }}" | python -m json.tool
```
^^ if you were to change `registration_status` to `first_name` it does work, and this is exactly how the frontend is current configured to do it

The frontend code is like so:
```jsx
let user = this.state.user;
user.mlh = true;
user.registration_status = "registered";
this.setState({
	loading: true,
	profileMSG: null,
	user: user
}, () => {
	this.props.profile.Set(this.state.user, (msg) => {
		if (msg) {
			this.setState({
				loading: false,
				profileMSG: [1, msg]
			});
		} else {
			this.setState({
				loading: false,
				profileMSG: [0, "Profile Updated!"]
			});
		}
	});
});
```
All of the other updates are working, meaning whatever the user types in to the `<Form/>`, such as `first_name` or `last_name` are being updated in `lcs`, which is what this code does. The data fields `mlh` and `registration_status` do not change however

**Comment by shivanmodha** [comment] 2018-12-30 20:49
For now, we are assuming that if the user is able to click the form button, the user has checked both of the mlh checkboxes, because both of those checkboxes are marked as `required`

**Comment by thekabistro** [comment] 2018-12-30 21:03
@hemangandhi @Sail338 Any ideas why the LCS endpoint isn't letting the update go through?

@shivanmodha "Faking it" --> what you had already will do just fine for the initial launch

**Comment by Sail338** [comment] 2018-12-31 03:15
Whats the initial status of the user  and what error are you getting

**Comment by shivanmodha** [comment] 2018-12-31 08:17
The one that I was testing in that curl is
```
"registration_status": "waitlist",
```

Oddly enough, that brings up a good point, because on another test, if the initial "registration_status = unregistered", the update in the frontend works...so now i'm confused

**Comment by Sail338** [comment] 2018-12-31 16:10
@shivanmodha this is working as intended. LCS maintains a state machine for registration status, meaning only certain registration status can move to others. https://github.com/HackRU/lcs/blob/master/validate.py see the validate_updates method and the state graph. (In your initial status waitlist is an end state and only an ADMIN can check them in)

**Closed by Sail338** 2018-12-31 16:10 UTC
Labels: bug, very-important
